package com.meridiantrust.sentinel.service;
import com.meridiantrust.sentinel.api.Dto.*; import com.meridiantrust.sentinel.domain.Domain.*; import com.meridiantrust.sentinel.repo.Repositories.*; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*; import java.util.stream.*;
@Service public class SentinelService { final Customers customers; final Accounts accounts; final Txs txs; final Alerts alerts; final Cases cases; final Audits audits; final Rules rules; final Fx fx;
 public SentinelService(Customers c,Accounts a,Txs t,Alerts al,Cases ca,Audits au,Rules r,Fx f){customers=c;accounts=a;txs=t;alerts=al;cases=ca;audits=au;rules=r;fx=f;}
 @Transactional public Customer customer(CustomerIn in){ if(customers.findByExternalId(in.externalId()).isPresent()) throw new IllegalArgumentException("customer externalId already exists"); return customers.save(new Customer(in.externalId(),in.fullName(),Optional.ofNullable(in.kycRisk()).orElse("MEDIUM"),in.country())); }
 @Transactional public Account account(AccountIn in){ Customer c=customers.findByExternalId(in.customerExternalId()).orElseThrow(()->new NoSuchElementException("customer not found")); if(accounts.findByAccountNumber(in.accountNumber()).isPresent())throw new IllegalArgumentException("account already exists"); Account a=new Account(in.accountNumber(),c);a.type=Optional.ofNullable(in.type()).orElse("SAVINGS");a.currency=Optional.ofNullable(in.currency()).orElse("INR");a.riskRating=Optional.ofNullable(in.riskRating()).orElse("MEDIUM");return accounts.save(a); }
 @Transactional public Tx transaction(TxIn in){ if(txs.existsByExternalId(in.externalId())) throw new IllegalArgumentException("transaction externalId already exists"); Account a=accounts.findByAccountNumber(in.accountNumber()).orElseThrow(()->new NoSuchElementException("account not found")); FxRate rate=fx.findById(in.currency()).orElseThrow(()->new IllegalArgumentException("No configured FX rate for "+in.currency())); Tx t=new Tx();t.externalId=in.externalId();t.account=a;t.amount=in.amount();t.currency=in.currency();t.normalizedAmount=in.amount().multiply(rate.inrRate);t.direction=Direction.valueOf(in.direction().toUpperCase());t.counterparty=in.counterparty();t.jurisdiction=in.jurisdiction().toUpperCase();t.channel=in.channel();t.timestamp=in.timestamp();t=txs.save(t); evaluate(t);return t; }
 RuleConfig cfg(String c){return rules.findById(c).orElseThrow();} void hit(Tx t,String code,String key,String explanation,String evidence){RuleConfig c=cfg(code);if(!c.enabled)return; alerts.findByAccountIdAndRuleCodeAndDedupeKey(t.account.id,code,key).orElseGet(()->{Alert a=new Alert();a.account=t.account;a.ruleCode=code;a.dedupeKey=key;a.riskScore=c.score;a.explanation=explanation;a.evidence=evidence; a=alerts.save(a);audit("ALERT",a.id,"CREATED","system",explanation);return a;});}
 void evaluate(Tx t){ Instant from=t.timestamp.minus(Duration.ofHours(48)); String day=t.timestamp.toString().substring(0,10); BigDecimal value=t.normalizedAmount;
  if(value.compareTo(cfg("CTR").threshold)>=0)hit(t,"CTR",day,"Single transaction meets the INR "+cfg("CTR").threshold+" reporting threshold.",t.externalId);
  if(Set.of("IR","KP","SY","AF").contains(t.jurisdiction))hit(t,"HIGH_RISK",day,"Transaction involves configured high-risk jurisdiction: "+t.jurisdiction+".",t.externalId);
  List<Tx> w=txs.findByAccountIdAndTimestampBetween(t.account.id,t.timestamp.minus(Duration.ofHours(24)),t.timestamp.plusSeconds(1)); BigDecimal low=cfg("STRUCTURING").threshold.subtract(new BigDecimal("1000")); List<Tx> near=w.stream().filter(x->x.normalizedAmount.compareTo(low)>=0&&x.normalizedAmount.compareTo(cfg("CTR").threshold)<0).toList(); if(near.size()>=3)hit(t,"STRUCTURING",day,"Three or more transactions in the INR 9,000–9,999 just-below-threshold band within 24 hours.",near.stream().map(x->x.externalId).collect(Collectors.joining(",")));
  if(t.direction==Direction.DEBIT){ List<Tx> credits=txs.findByAccountIdAndTimestampBetween(t.account.id,from,t.timestamp).stream().filter(x->x.direction==Direction.CREDIT).toList(); BigDecimal deposited=credits.stream().map(x->x.normalizedAmount).reduce(BigDecimal.ZERO,BigDecimal::add); if(deposited.signum()>0&&value.compareTo(deposited.multiply(new BigDecimal("0.80")))>=0)hit(t,"RAPID_MOVEMENT",day,"At least 80% of deposited funds moved out within 48 hours.",credits.stream().map(x->x.externalId).collect(Collectors.joining(","))+","+t.externalId); }
  List<Tx> history=txs.findByAccountCustomerIdAndTimestampBetween(t.account.customer.id,t.timestamp.minus(Duration.ofDays(90)),t.timestamp); BigDecimal historic=history.stream().map(x->x.normalizedAmount).reduce(BigDecimal.ZERO,BigDecimal::add).divide(BigDecimal.valueOf(90),2,RoundingMode.HALF_UP); BigDecimal daily=w.stream().map(x->x.normalizedAmount).reduce(BigDecimal.ZERO,BigDecimal::add); if(historic.signum()>0&&daily.compareTo(historic.multiply(BigDecimal.valueOf(3)))>0)hit(t,"BEHAVIOR",day,"Daily transaction value is over 3x the 90-day daily average.",t.externalId);
 }
 public List<Alert> queue(){return alerts.findAllByOrderByRiskScoreDescCreatedAtDesc();} @Transactional public Alert disposition(Long id,DispositionIn in,String actor){Alert a=alerts.findById(id).orElseThrow(()->new NoSuchElementException("alert not found"));a.status=AlertStatus.valueOf(in.status().toUpperCase());a.dispositionReason=in.reason();a.dispositionBy=actor;a=alerts.save(a);audit("ALERT",id,"DISPOSITIONED",actor,in.reason());return a;} @Transactional public Case createCase(Long alertId,String actor){Alert a=alerts.findById(alertId).orElseThrow();Case c=new Case();c.customer=a.account.customer;c.title="Investigation for alert #"+a.id;c.owner=actor;c=cases.save(c);audit("CASE",c.id,"CREATED",actor,"Created from alert "+alertId);return c;} public void audit(String type,Long id,String action,String actor,String detail){Audit x=new Audit();x.entityType=type;x.entityId=id;x.action=action;x.actor=actor;x.detail=detail;audits.save(x);} }
