package com.meridiantrust.sentinel.domain;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
public final class Domain { private Domain(){} public enum Direction { CREDIT, DEBIT } public enum AlertStatus { OPEN, IN_REVIEW, CLEARED, ESCALATED } public enum CaseStatus { OPEN, CLOSED }
 @Entity @Table(name="customers") public static class Customer { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @Column(unique=true,nullable=false) public String externalId; public String fullName; public String kycRisk="MEDIUM"; public String country; public Customer(){} public Customer(String ext,String name,String risk,String country){externalId=ext;fullName=name;kycRisk=risk;this.country=country;} }
 @Entity @Table(name="accounts") public static class Account { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @Column(unique=true,nullable=false) public String accountNumber; @ManyToOne(optional=false) public Customer customer; public String type; public String currency="INR"; public LocalDate openedOn; public String riskRating="MEDIUM"; public Account(){} public Account(String n,Customer c){accountNumber=n;customer=c;type="SAVINGS";openedOn=LocalDate.now();} }
 @Entity @Table(name="transactions", indexes=@Index(name="idx_tx_account_time",columnList="account_id,timestamp")) public static class Tx { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @Column(unique=true,nullable=false) public String externalId; @ManyToOne(optional=false) public Account account; @Enumerated(EnumType.STRING) public Direction direction; public BigDecimal amount; public BigDecimal normalizedAmount; public String currency; public String counterparty; public String jurisdiction; public String channel; public Instant timestamp; public Tx(){} }
 @Entity @Table(name="alerts",uniqueConstraints=@UniqueConstraint(name="uk_alert_dedupe",columnNames={"account_id","rule_code","dedupe_key"})) public static class Alert { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @ManyToOne(optional=false) public Account account; public String ruleCode; public String dedupeKey; public int riskScore; @Enumerated(EnumType.STRING) public AlertStatus status=AlertStatus.OPEN; @Column(length=4000) public String explanation; @Column(length=4000) public String evidence; public Instant createdAt=Instant.now(); public String dispositionReason; public String dispositionBy; }
 @Entity @Table(name="cases") public static class Case { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; @ManyToOne(optional=false) public Customer customer; public String title; @Enumerated(EnumType.STRING) public CaseStatus status=CaseStatus.OPEN; public String owner; public Instant createdAt=Instant.now(); }
 @Entity @Table(name="audit_events") public static class Audit { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) public Long id; public String entityType; public Long entityId; public String action; public String actor; public Instant occurredAt=Instant.now(); @Column(length=2000) public String detail; }
 @Entity @Table(name="rule_configs") public static class RuleConfig { @Id public String code; public boolean enabled=true; public BigDecimal threshold; public int windowHours; public int score; public RuleConfig(){} public RuleConfig(String c,BigDecimal t,int h,int s){code=c;threshold=t;windowHours=h;score=s;} }
 @Entity @Table(name="exchange_rates") public static class FxRate { @Id public String currency; public BigDecimal inrRate; public FxRate(){} public FxRate(String c,BigDecimal r){currency=c;inrRate=r;} }
}
